#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace AnimBP_NPC_035_VoiceJournal { struct FAnimBlueprintGeneratedConstantData; }

namespace NPC_039_A101_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_SMG_1003_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Wire_0LT_F { struct FAnimBlueprintGeneratedConstantData; }

namespace Locomotion_2HV_M { struct FAnimBlueprintGeneratedConstantData; }

namespace Locomotion_2LT_F { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_CampTank { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_003_U_VAR_BODY_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_MIS_VulgusController { struct FAnimBlueprintGeneratedConstantData; }

namespace SR { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_CampTank_Cannon { struct FAnimBlueprintGeneratedConstantData; }

namespace Locomotion_2LT_M { struct FAnimBlueprintGeneratedConstantData; }

namespace F_AR { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_034_TextJournal { struct FAnimBlueprintGeneratedConstantData; }

namespace UpperBody_F_003_Skil04 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_INTER_VulgusBox { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SCR_1008 { struct FAnimBlueprintGeneratedConstantData; }

namespace AR { struct FAnimBlueprintGeneratedConstantData; }

namespace Invasion_EnergyEmitter { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_TR_1001_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace F_HG_1001 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_009_Jeffer_Barricade01B { struct FAnimBlueprintGeneratedConstantData; }

namespace MainForServer { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SMG_1005 { struct FAnimBlueprintGeneratedConstantData; }

namespace Specification { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_003_A_VAR_HEAD_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace F_AR_1003 { struct FAnimBlueprintGeneratedConstantData; }

namespace Slot_0LT { struct FAnimBlueprintGeneratedConstantData; }

namespace F_HG { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_NPC_034_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_NPC_038_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_NPC_033_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace Ability_0HV_M { struct FAnimBlueprintGeneratedConstantData; }

namespace HG { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_033_Workbench { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MG { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_NPC_002_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_006_Macus { struct FAnimBlueprintGeneratedConstantData; }

namespace BR { struct FAnimBlueprintGeneratedConstantData; }

namespace SR_1007 { struct FAnimBlueprintGeneratedConstantData; }

namespace SCR_1003_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_039_Eckert { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_002_A_VAR_BODY_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace Ability_0LT_M { struct FAnimBlueprintGeneratedConstantData; }

namespace ALNC { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_Sec_Invasion_EnergyEmitter { struct FAnimBlueprintGeneratedConstantData; }

namespace SCR { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_004_A_VAR_BODY_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_038_Harris { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_NPC_006_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_Bunny_Operate { struct FAnimBlueprintGeneratedConstantData; }

namespace F_BR { struct FAnimBlueprintGeneratedConstantData; }

namespace Wire_0HV_M { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SR { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_004_A_VAR_HEAD_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_INTER_GasTank { struct FAnimBlueprintGeneratedConstantData; }

namespace HG_1001_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace Wire_2HV_M { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_004_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_003_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SCR { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_AR_1003_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_032_Transportstorage { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_SCR_1008_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace TR_1001_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace Wire_2HV_F { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_CampTank_Core { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_040_CombatSupportDroid { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_Head_Base { struct FAnimBlueprintGeneratedConstantData; }

namespace Locomotion_2HV_F { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_NPC_009_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace SMG_1005 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_002_MissionVeacon { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SG { struct FAnimBlueprintGeneratedConstantData; }

namespace F_TR_1001 { struct FAnimBlueprintGeneratedConstantData; }

namespace WC_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_002_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_MG_1007_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_SG_1003_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace CustomHead { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MG_1007 { struct FAnimBlueprintGeneratedConstantData; }

namespace SCR_1008_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SR_1007 { struct FAnimBlueprintGeneratedConstantData; }

namespace SG { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_006_A_VAR_BODY_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_MOB_CMN_1003_A { struct FAnimBlueprintGeneratedConstantData; }

namespace M_001_BP { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_INTER_MilitarySupplies { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MG_1003 { struct FAnimBlueprintGeneratedConstantData; }

namespace Ability_2HV_M { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_Sub_Camp { struct FAnimBlueprintGeneratedConstantData; }

namespace M_001_Specification_BP { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_SR_1007_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_SK_Vulgus_Carrier_Darkness_Skeleton { struct FAnimBlueprintGeneratedConstantData; }

namespace MOB_CMN_1024_A_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Wire_0LT_M { struct FAnimBlueprintGeneratedConstantData; }

namespace Ability_2HV_F { struct FAnimBlueprintGeneratedConstantData; }

namespace Wire_2LT_M { struct FAnimBlueprintGeneratedConstantData; }

namespace Locomotion_0HV_M { struct FAnimBlueprintGeneratedConstantData; }

namespace Ability_0LT_F { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SR_1002 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_NPC_032_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace F_TR { struct FAnimBlueprintGeneratedConstantData; }

namespace WC_Hook_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_VoidVaultStabilizer { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_009_Jeffer_Barricade01A { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_009_Jeffer_Checkpoint { struct FAnimBlueprintGeneratedConstantData; }

namespace MG { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_009_Jeffer { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_NPC_Dialog { struct FAnimBlueprintGeneratedConstantData; }

namespace AR_1003_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SCR_1003 { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_SCR_1003_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SR_1002_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_MIS_Antenna { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_SR_1002_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Locomotion_0LT_F { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_SK_Vulgus_Tunnel { struct FAnimBlueprintGeneratedConstantData; }

namespace Locomotion_0LT_M { struct FAnimBlueprintGeneratedConstantData; }

namespace F_Invasion_EnergyEmitte { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_MIS_AlbionRepeater { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_MOB_CMN_1024_A { struct FAnimBlueprintGeneratedConstantData; }

namespace MG_1003 { struct FAnimBlueprintGeneratedConstantData; }

namespace SMG { struct FAnimBlueprintGeneratedConstantData; }

namespace WP_DeadRoom_1001_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_001_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_003_U_VAR_HEAD_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace CustomHead_Child { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_001_U_VAR_BODY_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace MOB_BASE_DUMMY_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace MG_1007_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_CampSimple { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_ACC_CHEST_016A { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SG_1003 { struct FAnimBlueprintGeneratedConstantData; }

namespace SG_1003_0 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_006_A_VAR_HEAD_000 { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Sec_PC_006_A0101 { struct FAnimBlueprintGeneratedConstantData; }

namespace F_SMG { struct FAnimBlueprintGeneratedConstantData; }

namespace RW_SMG_1005_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Ability_2LT_M { struct FAnimBlueprintGeneratedConstantData; }

namespace Slot_2LT { struct FAnimBlueprintGeneratedConstantData; }

namespace MOB_CMN_1003_A_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Ability_2LT_F { struct FAnimBlueprintGeneratedConstantData; }

namespace Wire_2LT_F { struct FAnimBlueprintGeneratedConstantData; }


namespace Wire
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace UpperBody
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace InventoryPreviewAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace WP_Invasion_EnergyEmitter_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_PC_003_A0101
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Main
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Locomotion
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace RW_LNC_1001_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace AnimBP_NpcBase
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Slot_2HV
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace AnimBP_NPC_FullBody
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace BP_Sec_PC_003_Prop01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Slot_1HV
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace AnimBP_NPC_Facial
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace MOB_BASE_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace AnimBP_NPC_LookAt
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Slot_0HV
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace IK
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace RW_HG_1001_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Ability
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}
